const P=window.GLAM_PRODUCTS;
const Q=s=>document.querySelector(s),M=n=>'Gs. '+new Intl.NumberFormat('es-PY').format(n||0),V=p=>p.variants||[],G=p=>(p.groupSkus||[]).map(s=>P.find(x=>x.sku===s)).filter(Boolean);
let cart=JSON.parse(localStorage.getItem('glamcart')||'{}'),active=null;
const sale=p=>Math.round(p.price*(1-window.GLAM_PROMOTION.rate)), imageFor=(p,v)=>p.variantImages?.[v]||p.image;
const key=(p,v='')=>p.sku+'::'+v,parseKey=k=>{let[a,b='']=k.split('::');return[P.find(p=>p.sku===a),b]};
function syncUI(){let on=Q('#m').classList.contains('on')||Q('#d').classList.contains('on');Q('#o').classList.toggle('on',on);document.body.classList.toggle('ui-open',on)}
function save(){localStorage.setItem('glamcart',JSON.stringify(cart));draw()}
function add(p,v=''){let k=key(p,v);cart[k]=(cart[k]||0)+1;save();openD()}
function qty(k,d){cart[k]=(cart[k]||0)+d;if(cart[k]<=0)delete cart[k];save()}
function searchText(p){let members=G(p);return[p.name,p.sku,p.material,...V(p),...members.flatMap(x=>[x.name,x.sku,x.material])].join(' ').toLowerCase()}
function filt(){let q=Q('#s').value.toLowerCase(),c=Q('#c').value,a=P.filter(p=>!p.hidden&&(!c||p.category===c||G(p).some(x=>x.category===c))&&(!q||searchText(p).includes(q)));let o=Q('#sort').value;if(o==='low')a.sort((x,y)=>groupMin(x)-groupMin(y));else if(o==='high')a.sort((x,y)=>groupMax(y)-groupMax(x));else a.sort((x,y)=>x.name.localeCompare(y.name,'es'));return a}
function groupMin(p){let g=G(p);return g.length?Math.min(...g.map(x=>x.price)):p.price}
function groupMax(p){let g=G(p);return g.length?Math.max(...g.map(x=>x.price)):p.price}
function priceLabel(p){let g=G(p),base=groupMin(p);return (g.length?'Desde ':'')+'<span class="sale-price">'+M(Math.round(base*.9))+'</span> <del>'+M(base)+'</del>'}
function cleanGroupName(p,x){return p.groupStrip?x.name.replace(p.groupStrip,''):x.name}
function optionLabel(p){let g=G(p);if(g.length)return p.groupLabel||g.map(x=>cleanGroupName(p,x)).join(' / ');if(p.variantSummary)return p.variantSummary;return V(p).length?V(p).join(' / '):''}
function choiceCount(p){let g=G(p);if(g.length)return g.length+' modelos';if(V(p).length)return V(p).length+' opciones';return p.sku}
function render(){let a=filt();Q('#count').textContent=a.length+' piezas';Q('#grid').innerHTML=a.map(p=>{let g=G(p),hasChoice=g.length||V(p).length;return`<article class="card"><div class="pic" onclick="detail('${p.sku}')">${p.image?`<img loading="lazy" src="${p.image}" alt="${p.name}">`:`<div class="ph">Foto en actualización</div>`}</div><div class="meta">${p.category}</div><div class="row"><h3>${p.name}</h3><div class="price">${priceLabel(p)}</div></div><div class="sku">${hasChoice?choiceCount(p)+' · ':p.sku}${optionLabel(p)}</div><div class="buttons"><button class="add" onclick="quickAdd('${p.sku}')">${hasChoice?'Elegir opción':'Agregar al carrito'}</button><button class="view" onclick="detail('${p.sku}')">Ver</button></div></article>`}).join('')}
function quickAdd(sku){let p=P.find(x=>x.sku===sku);if(G(p).length||V(p).length)return detail(sku);add(p)}
function setGroupChoice(p){Q('#mpr').innerHTML=priceLabel(p);Q('#msku').textContent=p.sku;Q('#mmat').textContent=p.material||'Consultar';Q('#mst').textContent=p.stock||'Consultar'}
function detail(sku){Q('#stoneColorBlock')?.remove();Q('#d').classList.remove('on');active=P.find(p=>p.sku===sku);let gs=G(active),vs=V(active);Q('#mcat').textContent=active.category;Q('#mn').textContent=active.name;Q('#mpr').innerHTML=priceLabel(gs.length?gs[0]:active);Q('#msku').textContent=gs.length?gs[0].sku:active.sku;Q('#mmat').textContent=(gs.length?gs[0].material:active.material)||'Consultar';Q('#mst').textContent=(gs.length?gs[0].stock:active.stock)||'Consultar';Q('#mp').innerHTML=active.image?`<img src="${active.image}" alt="${active.name}">`:'<div class="ph">Foto en actualización</div>';Q('#vb').style.display=(gs.length||vs.length)?'block':'none';let label=Q('#vb label');if(gs.length){label.textContent=active.groupSelectLabel||'Elegí el modelo';Q('#v').innerHTML=gs.map(x=>`<option value="${x.sku}">${cleanGroupName(active,x)} — ${M(sale(x))}</option>`).join('');Q('#v').onchange=e=>setGroupChoice(P.find(x=>x.sku===e.target.value));Q('#ma').onclick=()=>{let p=P.find(x=>x.sku===Q('#v').value);add(p)}}else{label.textContent=active.variantLabel||'Elegí una opción';Q('#v').innerHTML=vs.map(v=>`<option>${v}</option>`).join('');Q('#v').onchange=null;Q('#ma').onclick=()=>add(active,vs.length?Q('#v').value:'')}if(active.stoneCollection)setupStones(active);Q('#m').classList.add('on');syncUI()}
function setupStones(collection){
  const block=document.createElement('div');block.id='stoneColorBlock';block.className='variant-block';
  block.innerHTML='<label for="stoneColor">Elegí el color</label><select id="stoneColor">'+collection.colors.map(c=>'<option>'+c+'</option>').join('')+'</select>';
  Q('#vb').before(block);Q('#vb label').textContent='Elegí la pieza';
  function choosePiece(){const p=P.find(x=>x.sku===Q('#v').value);setGroupChoice(p);Q('#mp').innerHTML='<img src="'+collection.colorPhotos[Q('#stoneColor').value]+'" alt="Colección de piedras · '+Q('#stoneColor').value+'">'}
  function chooseColor(){const color=Q('#stoneColor').value,previous=Q('#v').value;Q('#v').innerHTML=G(collection).filter(p=>p.variants.includes(color)).map(p=>'<option value="'+p.sku+'">'+p.name+' — '+M(sale(p))+'</option>').join('');if([...Q('#v').options].some(o=>o.value===previous))Q('#v').value=previous;choosePiece()}
  Q('#stoneColor').onchange=chooseColor;Q('#v').onchange=choosePiece;
  Q('#ma').onclick=()=>add(P.find(p=>p.sku===Q('#v').value),Q('#stoneColor').value);chooseColor();
}
function closeM(){Q('#m').classList.remove('on');syncUI()}
function openD(){Q('#m').classList.remove('on');Q('#d').classList.add('on');syncUI()}
function closeD(){Q('#d').classList.remove('on');syncUI()}
function closeAll(){Q('#m').classList.remove('on');Q('#d').classList.remove('on');syncUI()}
function draw(){let ks=Object.keys(cart),ct=0,t=0;Q('#items').innerHTML=ks.length?ks.map(k=>{let[p,v]=parseKey(k),q=cart[k];if(!p)return'';ct+=q;t+=sale(p)*q;return`<div class="ci">${imageFor(p,v)?`<img src="${imageFor(p,v)}" alt="${p.name}">`:`<div class="thumb">GJ</div>`}<div><div class="sku">${p.sku}</div><h4>${p.name}</h4>${v?`<div class="meta">${v}</div>`:''}<div class="price">${M(sale(p))} <del>${M(p.price)}</del></div><div class="q"><button aria-label="Quitar uno" onclick="qty('${k}',-1)">−</button><span>${q}</span><button aria-label="Agregar uno" onclick="qty('${k}',1)">+</button></div></div><button class="x" aria-label="Eliminar producto" onclick="qty('${k}',-${q})">×</button></div>`}).join(''):'<p style="text-align:center;padding:35px 10px;color:#716b62;font-size:11px">Tu carrito está vacío. Agregá una pieza para comenzar.</p>';Q('#n').textContent=ct;Q('#total').textContent=M(t);Q('#savings').textContent=M(ks.reduce((sum,k)=>{let[p]=parseKey(k);return sum+(p?(p.price-sale(p))*cart[k]:0)},0))}
function checkout(){let ks=Object.keys(cart);if(!ks.length)return alert('Tu carrito está vacío.');let orderName=Q('#orderName').value.trim(),delivery=Q('input[name="delivery"]:checked'),invoice=Q('#invoice').checked;if(!orderName){Q('#orderName').focus();return alert('Ingresá a nombre de quién se realiza el pedido.')}if(!delivery)return alert('Elegí una forma de entrega.');let billName='',ruc='',billPhone='',billEmail='';if(invoice){billName=Q('#billName').value.trim();ruc=Q('#ruc').value.trim();billPhone=Q('#billPhone').value.trim();billEmail=Q('#billEmail').value.trim();if(!billName){Q('#billName').focus();return alert('Para solicitar factura, ingresá el nombre o razón social.')}if(!ruc){Q('#ruc').focus();return alert('Para solicitar factura, ingresá el RUC.')}}let t=0,base=0,lines=ks.filter(k=>parseKey(k)[0]).map(k=>{let[p,v]=parseKey(k),q=cart[k];t+=sale(p)*q;base+=p.price*q;return`• ${q} × ${p.name}${v?' — '+v:''} (${p.sku}) — ${M(sale(p)*q)}`}),nl=String.fromCharCode(10),parts=['Hola Glam Joyas ✨','Quiero realizar este pedido:','',...lines,'','Subtotal: '+M(base),'Descuento de inauguración (10%): −'+M(base-t),'Total con descuento: '+M(t),'','A nombre de: '+orderName,'Entrega: '+delivery.value];if(invoice){parts.push('','Factura: Sí','Nombre / Razón social: '+billName,'RUC: '+ruc);if(billPhone)parts.push('Teléfono: '+billPhone);if(billEmail)parts.push('Correo: '+billEmail)}else parts.push('Factura: No');parts.push('','¿Me confirman disponibilidad, entrega y forma de pago?');window.open('https://wa.me/595995360542?text='+encodeURIComponent(parts.join(nl)),'_blank')}
[...new Set(P.filter(p=>!p.hidden).map(p=>p.category))].sort().forEach(x=>Q('#c').innerHTML+=`<option>${x}</option>`);Q('#s').oninput=render;Q('#c').onchange=render;Q('#sort').onchange=render;Q('#bag').onclick=openD;Q('#xd').onclick=closeD;Q('#xm').onclick=closeM;Q('#o').onclick=closeAll;Q('#wa').onclick=checkout;Q('#invoice').onchange=e=>Q('#invoiceFields').classList.toggle('on',e.target.checked);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAll()});render();draw();
