'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>'Gs. '+new Intl.NumberFormat('es-PY').format(n),norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
let data,csrf='',filter='all',selected=null,editing=null,photo='',busy=false,photoBusy=false;
async function api(action,body){const r=await fetch('/api/local?action='+action,{cache:'no-store',method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-Glam-CSRF':csrf}:{},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'No se pudo completar.');return d;}
async function load(){data=await api('list');render();}
const isPublic=sku=>data.publicProducts.some(p=>p.sku===sku);
function entries(){return [...data.publicProducts.filter(p=>!p.hidden).map(p=>({...p,public:true})),...data.products.filter(p=>!isPublic(p.sku)).map(p=>({...p,public:false}))];}
function src(p){return p.public?p.image:'/api/local?action=photo&sku='+encodeURIComponent(p.sku)+'&v='+encodeURIComponent(p.photoSha);}
function members(p){return p.public&&p.groupSkus?.length?p.groupSkus.map(sku=>data.publicProducts.find(p=>p.sku===sku)).filter(Boolean):[p];}
function render(){const q=norm($('#search').value),cat=$('#category').value;const list=entries().filter(p=>(filter==='archived'?p.archived:!p.archived)&&(filter!=='local'||!p.public)&&(filter!=='public'||p.public)&&(!cat||p.category===cat)&&(!q||norm([p.name,p.sku,...(p.variants||[]),...members(p).map(x=>x.name+' '+x.sku)].join(' ')).includes(q))).sort((a,b)=>a.name.localeCompare(b.name,'es'));$('#count').textContent=list.length+' joyas';$('#cards').innerHTML=list.map(p=>`<button class="card" data-sku="${esc(p.sku)}"><img loading="lazy" src="${esc(src(p))}" alt=""><div class="info"><span class="badge">${p.public?'En la web':'Solo local'}${p.archived?' · Archivada':''}</span><h2>${esc(p.name)}</h2><small>${esc(p.sku)}</small><strong>${members(p).length>1||p.consultOnly?'Desde ':''}${money(Math.min(...members(p).map(x=>x.price)))}</strong><small>Precio normal al público</small></div></button>`).join('')||'<p>No encontramos joyas. Probá otra búsqueda.</p>';}
function detail(sku){selected=entries().find(p=>p.sku===sku);const p=selected;$('#detailTitle').textContent=p.name;$('#detailPhoto').src=src(p);$('#detailPhoto').alt=p.name;$('#detailBody').innerHTML=`<p><span class="badge">${p.public?'En la web':'Solo local'}</span> · ${esc(p.sku)}</p>`+members(p).map(x=>`<div class="piece">${esc(x.name)}<strong>${money(x.price)}</strong><small>Precio normal al público${p.public?' · Promo web: '+money(Math.round(x.price*.9)):''}</small><p>${esc((x.variants||[]).join(' / '))}</p>${x.consultOnly?'<p>Desde este precio; consultar según tamaño.</p>':''}</div>`).join('');$('#publish').hidden=p.public||p.archived;$('#edit').textContent=p.public?'Editar en el panel web':'Editar';$('#detailError').textContent='';$('#detail').showModal();}
function editor(p){editing=p||null;photo='';$('#form').reset();$('#sku').readOnly=!!p;$('#name').value=p?.name||'';$('#sku').value=p?.sku||'';$('#price').value=p?.price||'';$('#variants').value=(p?.variants||[]).join('\n');if(p)$('#editCategory').value=p.category;$('#archived').checked=!!p?.archived;$('#preview').hidden=!p;if(p)$('#preview').src=src(p);$('#error').textContent='';$('#editor').showModal();}
$('#search').oninput=render;$('#category').onchange=render;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render();});$('#cards').onclick=e=>{const b=e.target.closest('[data-sku]');if(b)detail(b.dataset.sku);};$('#new').onclick=()=>editor(null);$('#closeDetail').onclick=()=>$('#detail').close();$('#closeEditor').onclick=()=>{if(!busy)$('#editor').close();};$('#edit').onclick=()=>{if(selected.public){location.href='/admin';return;}$('#detail').close();editor(selected);};$('#refresh').onclick=async()=>{try{await load();$('#message').textContent='Lista actualizada.';}catch(e){$('#message').textContent=e.message;}};
$('#upload').onchange=async()=>{const f=$('#upload').files[0];if(!f)return;photoBusy=true;$('#save').disabled=true;try{if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>10485760)throw Error('Elegí JPG, PNG o WebP de hasta 10 MB.');const b=await createImageBitmap(f);if(b.width*b.height>40000000){b.close();throw Error('La imagen es demasiado grande.');}const s=Math.min(1,1200/Math.max(b.width,b.height)),c=document.createElement('canvas');c.width=Math.round(b.width*s);c.height=Math.round(b.height*s);const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(b,0,0,c.width,c.height);b.close();let quality=.8,v=c.toDataURL('image/jpeg',quality);while(v.length>850000&&quality>.3){quality-=.1;v=c.toDataURL('image/jpeg',quality);}if(v.length>900000)throw Error('Probá con una foto más pequeña.');photo=v;$('#preview').src=v;$('#preview').hidden=false;$('#error').textContent='';}catch(e){$('#error').textContent=e.message;}finally{photoBusy=false;$('#save').disabled=false;}};
$('#form').onsubmit=async e=>{e.preventDefault();if(busy||photoBusy)return;if(!editing&&!photo){$('#error').textContent='Agregá una foto.';return;}busy=true;$('#save').disabled=true;$('#error').textContent='Guardando de forma privada…';const variants=$('#variants').value.split('\n').map(s=>s.trim()).filter(Boolean);const product={sku:$('#sku').value.trim(),name:$('#name').value.trim(),category:$('#editCategory').value,price:Number($('#price').value),variants,available:editing?.available!==false,archived:$('#archived').checked,optionAvailability:Object.fromEntries(variants.map(v=>[v,editing?.optionAvailability?.[v]!==false])),...(photo?{photo}:{})};try{await api('save',{baseSha:data.sha,product});$('#editor').close();await load();$('#message').textContent='Guardado en tu lista privada. Todavía no aparece en la web.';}catch(e){$('#error').textContent=e.message;}finally{busy=false;$('#save').disabled=false;}};
$('#publish').onclick=()=>{$('#confirmText').textContent=selected.name+' · '+money(selected.price)+' (precio normal)';$('#publishError').textContent='';$('#confirm').showModal();};$('#cancelPublish').onclick=()=>{if(!busy)$('#confirm').close();};$('#confirm').addEventListener('cancel',e=>{if(busy)e.preventDefault();});$('#editor').addEventListener('cancel',e=>{if(busy)e.preventDefault();});
$('#confirmPublish').onclick=async()=>{if(busy)return;busy=true;$('#confirmPublish').disabled=true;$('#cancelPublish').disabled=true;$('#publishError').textContent='Publicando…';try{await api('publish',{baseSha:data.sha,publicSha:data.publicSha,sku:selected.sku});$('#confirm').close();$('#detail').close();await load();$('#message').textContent='Enviado a GitHub. Vercel actualizará la web en unos momentos. Podés consultar su estado en el panel web.';}catch(e){$('#publishError').textContent=e.message;}finally{busy=false;$('#confirmPublish').disabled=false;$('#cancelPublish').disabled=false;}};
(async()=>{try{const r=await fetch('/api/admin?action=session',{cache:'no-store'}),s=await r.json();if(!r.ok)throw Error(s.error);csrf=s.csrf;await load();const cats=[...new Set(data.publicProducts.map(p=>p.category))].sort();for(const id of ['category','editCategory'])$('#'+id).insertAdjacentHTML('beforeend',cats.map(c=>`<option>${esc(c)}</option>`).join(''));$('#login').hidden=true;$('#app').hidden=false;}catch(e){$('#loginText').textContent=e.message;}})();
